theme: jekyll-theme-cayman
title: Android Camera/Camerax
description: My Progress App for Grand Valley State University Mobile Development Course Fall 2020  
markdown: kramdown
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
